#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""waf_detector/fingerprints.py — WAF 指纹数据库 (v2.0 — 150+ 厂商)
包含 150+ WAF 厂商的指纹信息，覆盖国际云WAF、国产WAF、开源WAF、硬件WAF、新兴WAF。

每个 WAF 条目包含以下字段:
    - category: WAF 类别 (cloud/hardware/software/cdn/saas)
    - headers: 响应头指纹 (header_name -> 正则模式列表)
    - cookies: Cookie 指纹 (cookie 名称模式列表)
    - body: 响应正文关键词列表
    - status_codes: 常见拦截状态码
    - title: 拦截页面标题列表
    - active_probe: 主动探测配置 (path + contains)
    - behavior: WAF 行为特征 (challenge 类型 + cookie 名称)
    - asn: 关联 ASN 列表
    - confidence_weight: 置信权重 (0.0-1.0)
"""

# ============================================================================
# WAF 指纹数据库
# ============================================================================

WAF_FINGERPRINTS = {

    # ========================================================================
    # 国际云 WAF (Cloud / SaaS WAF)
    # ========================================================================

    "Cloudflare": {
        "category": "cloud",
        "headers": {"server": ["cloudflare"], "cf-ray": [".*"], "cf-cache-status": [".*"], "cf-mitigated": [".*"]},
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance", "__cflb", "__cfcharset"],
        "body": ["cloudflare", "cf-browser-verification", "cf_chl_", "cloudflare-ray", "attention required"],
        "status_codes": [403, 503, 406, 429, 1020],
        "title": ["attention required! | cloudflare", "just a moment...", "cloudflare"],
        "active_probe": {"path": "/cdn-cgi/trace", "contains": ["cf-ray", "visit-scheme"]},
        "behavior": {"challenge": "javascript", "cookie_name": "cf_clearance"},
        "asn": ["AS13335"],
        "confidence_weight": 1.0,
    },
    "Cloudflare Enterprise": {
        "category": "cloud",
        "headers": {"server": ["cloudflare"], "cf-ray": [".*"], "cf-cache-status": [".*"], "cf-edge": [".*"]},
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance", "__cflb", "cf_chl_rc_z"],
        "body": ["cloudflare", "cf-browser-verification", "managed challenge"],
        "status_codes": [403, 503, 406, 429, 1020],
        "title": ["attention required! | cloudflare", "just a moment..."],
        "active_probe": {"path": "/cdn-cgi/trace", "contains": ["cf-ray", "visit-scheme"]},
        "behavior": {"challenge": "javascript", "cookie_name": "cf_clearance"},
        "asn": ["AS13335"],
        "confidence_weight": 1.0,
    },
    "Cloudflare Bot Management": {
        "category": "cloud",
        "headers": {"server": ["cloudflare"], "cf-ray": [".*"], "cf-bot": [".*"], "cf-mitigated": ["bot"]},
        "cookies": ["__cf_bm", "cf_clearance"],
        "body": ["cloudflare", "bot management", "managed challenge"],
        "status_codes": [403, 503, 429],
        "title": ["just a moment...", "attention required! | cloudflare"],
        "active_probe": {"path": "/cdn-cgi/trace", "contains": ["cf-ray"]},
        "behavior": {"challenge": "javascript", "cookie_name": "__cf_bm"},
        "asn": ["AS13335"],
        "confidence_weight": 0.95,
    },
    "AWS WAF": {
        "category": "cloud",
        "headers": {"x-amzn-requestid": [".*"], "x-amz-cf-id": [".*"], "via": ["cloudfront"]},
        "cookies": ["aws-waf-token"],
        "body": ["aws waf", "request blocked", "amzn"],
        "status_codes": [403, 400],
        "title": ["request blocked", "forbidden"],
        "active_probe": {"path": "/", "contains": ["x-amzn-requestid"]},
        "behavior": {"challenge": "token", "cookie_name": "aws-waf-token"},
        "asn": ["AS16509"],
        "confidence_weight": 0.95,
    },
    "AWS WAF v2": {
        "category": "cloud",
        "headers": {"x-amzn-requestid": [".*"], "x-amz-cf-id": [".*"], "via": ["cloudfront"], "x-amzn-waf": [".*"]},
        "cookies": ["aws-waf-token"],
        "body": ["aws waf", "wafv2", "request blocked"],
        "status_codes": [403, 400, 429],
        "title": ["request blocked", "forbidden"],
        "active_probe": {"path": "/", "contains": ["x-amzn-requestid"]},
        "behavior": {"challenge": "captcha", "cookie_name": "aws-waf-token"},
        "asn": ["AS16509"],
        "confidence_weight": 0.95,
    },
    "Akamai": {
        "category": "cloud",
        "headers": {"server": ["akamaighost"], "x-akamai-transformed": [".*"], "x-akamai-request-id": [".*"]},
        "cookies": ["AKA_A2", "ak_bmsc", "bm_sz", "bm_sv"],
        "body": ["akamai", "akamai technologies", "reference #", "access denied"],
        "status_codes": [403, 503, 400, 429],
        "title": ["access denied", "error", "you don't have permission"],
        "active_probe": {"path": "/", "contains": ["akamaighost"]},
        "behavior": {"challenge": "javascript", "cookie_name": "ak_bmsc"},
        "asn": ["AS20940", "AS16625"],
        "confidence_weight": 0.95,
    },
    "Imperva/Incapsula": {
        "category": "cloud",
        "headers": {"server": ["incapsula"], "x-iinfo": [".*"], "x-cdn": ["incapsula"]},
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_", "incap_visid_incap_"],
        "body": ["incapsula", "incap_ses", "request blocked", "powered by incapsula"],
        "status_codes": [403, 503, 406, 429],
        "title": ["request blocked", "access denied", "incapsula incident"],
        "active_probe": {"path": "/", "contains": ["incapsula"]},
        "behavior": {"challenge": "javascript", "cookie_name": "incap_ses_"},
        "asn": ["AS19551"],
        "confidence_weight": 0.95,
    },
    "Imperva Cloud WAF": {
        "category": "cloud",
        "headers": {"server": ["imperva"], "x-iinfo": [".*"], "x-cdn": ["imperva"]},
        "cookies": ["incap_ses_", "visid_incap_", "imperva_"],
        "body": ["imperva", "incapsula", "request blocked"],
        "status_codes": [403, 503, 406],
        "title": ["request blocked", "access denied"],
        "active_probe": {"path": "/", "contains": ["imperva"]},
        "behavior": {"challenge": "javascript", "cookie_name": "incap_ses_"},
        "asn": ["AS19551"],
        "confidence_weight": 0.95,
    },
    "Fastly": {
        "category": "cloud",
        "headers": {"server": ["fastly"], "x-served-by": ["cache"], "x-cache": [".*"], "x-fastly": [".*"]},
        "cookies": ["fastly_cdn", "fs_tls"],
        "body": ["fastly", "fastly error", "unknown domain"],
        "status_codes": [403, 503, 400],
        "title": ["fastly error", "unknown domain"],
        "active_probe": {"path": "/", "contains": ["fastly"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS54113"],
        "confidence_weight": 0.85,
    },
    "Fastly Next-Gen WAF": {
        "category": "cloud",
        "headers": {"server": ["fastly"], "x-signal-sciences": [".*"], "x-served-by": ["cache"]},
        "cookies": ["_sigil_", "ss_"],
        "body": ["signal sciences", "fastly next-gen", "request blocked"],
        "status_codes": [403, 429],
        "title": ["request blocked", "forbidden"],
        "active_probe": {"path": "/", "contains": ["signal sciences"]},
        "behavior": {"challenge": "none", "cookie_name": "_sigil_"},
        "asn": ["AS54113"],
        "confidence_weight": 0.9,
    },
    "Azure Front Door": {
        "category": "cloud",
        "headers": {"server": ["microsoft-azurefront", "azurefd"], "x-azure-ref": [".*"], "x-cache": [".*"]},
        "cookies": ["azurefd", "afdv2"],
        "body": ["azure front door", "microsoft azure", "request blocked"],
        "status_codes": [403, 503, 400],
        "title": ["request blocked", "our services aren't available"],
        "active_probe": {"path": "/", "contains": ["x-azure-ref"]},
        "behavior": {"challenge": "none", "cookie_name": "azurefd"},
        "asn": ["AS8075"],
        "confidence_weight": 0.9,
    },
    "Google Cloud Armor": {
        "category": "cloud",
        "headers": {"server": ["gunicorn", "google"], "x-google": [".*"], "via": ["google"]},
        "cookies": ["gclb", "google_cloud_armor"],
        "body": ["google cloud armor", "request blocked", "denied by"],
        "status_codes": [403, 429],
        "title": ["request blocked", "forbidden"],
        "active_probe": {"path": "/", "contains": ["google cloud armor"]},
        "behavior": {"challenge": "none", "cookie_name": "gclb"},
        "asn": ["AS15169", "AS396982"],
        "confidence_weight": 0.9,
    },
    "F5 ASM": {
        "category": "cloud",
        "headers": {"server": ["bigip", "f5"], "x-cdn": ["f5"]},
        "cookies": ["TS01", "BIGipServer", "f5_"],
        "body": ["f5", "asm", "big-ip", "the requested url was rejected"],
        "status_codes": [403, 503, 400],
        "title": ["request rejected", "error page"],
        "active_probe": {"path": "/", "contains": ["bigip"]},
        "behavior": {"challenge": "none", "cookie_name": "BIGipServer"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Citrix NetScaler": {
        "category": "cloud",
        "headers": {"server": ["citrix", "netscaler"], "via": ["citrix"]},
        "cookies": ["ns_af", "citrix_ns_id", "NSC_"],
        "body": ["citrix", "netscaler", "appfirewall"],
        "status_codes": [403, 503, 400],
        "title": ["access denied", "forbidden"],
        "active_probe": {"path": "/", "contains": ["citrix"]},
        "behavior": {"challenge": "none", "cookie_name": "ns_af"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Fortinet FortiWeb": {
        "category": "cloud",
        "headers": {"server": ["fortiweb", "fortinet"]},
        "cookies": ["fortiweb", "fb_waf"],
        "body": ["fortiweb", "fortinet", "web application firewall"],
        "status_codes": [403, 503],
        "title": ["access denied", "forbidden"],
        "active_probe": {"path": "/", "contains": ["fortiweb"]},
        "behavior": {"challenge": "none", "cookie_name": "fortiweb"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Radware": {
        "category": "cloud",
        "headers": {"server": ["radware"], "x-rdw": [".*"]},
        "cookies": ["rdw_", "radware"],
        "body": ["radware", "cloud waf", "request blocked"],
        "status_codes": [403, 503],
        "title": ["request blocked", "access denied"],
        "active_probe": {"path": "/", "contains": ["radware"]},
        "behavior": {"challenge": "javascript", "cookie_name": "rdw_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Radware Cloud WAF": {
        "category": "cloud",
        "headers": {"server": ["radware"], "x-rdw-cdn": [".*"]},
        "cookies": ["rdw_cloud", "radware_cloud"],
        "body": ["radware cloud", "cloud waf service"],
        "status_codes": [403, 503, 429],
        "title": ["access denied", "request blocked"],
        "active_probe": {"path": "/", "contains": ["radware"]},
        "behavior": {"challenge": "javascript", "cookie_name": "rdw_cloud"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Sucuri": {
        "category": "cloud",
        "headers": {"server": ["sucuri"], "x-sucuri-id": [".*"], "x-sucuri-cache": [".*"]},
        "cookies": ["sucuri_cloudproxy"],
        "body": ["sucuri", "sucuri webSite firewall", "access denied"],
        "status_codes": [403, 503, 406],
        "title": ["access denied - sucuri", "sucuri website firewall"],
        "active_probe": {"path": "/", "contains": ["sucuri"]},
        "behavior": {"challenge": "javascript", "cookie_name": "sucuri_cloudproxy"},
        "asn": ["AS399471"],
        "confidence_weight": 0.9,
    },
    "StackPath": {
        "category": "cloud",
        "headers": {"server": ["stackpath"], "x-sp-url": [".*"]},
        "cookies": ["sp_"],
        "body": ["stackpath", "request blocked"],
        "status_codes": [403, 503],
        "title": ["access denied", "request blocked"],
        "active_probe": {"path": "/", "contains": ["stackpath"]},
        "behavior": {"challenge": "none", "cookie_name": "sp_"},
        "asn": ["AS20454"],
        "confidence_weight": 0.8,
    },
    "Edgecast": {
        "category": "cloud",
        "headers": {"server": ["edgecast", "ecd"], "x-ec-debug": [".*"]},
        "cookies": ["ec_"],
        "body": ["edgecast", "verizon"],
        "status_codes": [403, 503],
        "title": ["error", "access denied"],
        "active_probe": {"path": "/", "contains": ["edgecast"]},
        "behavior": {"challenge": "none", "cookie_name": "ec_"},
        "asn": ["AS15133"],
        "confidence_weight": 0.8,
    },
    "CDN77": {
        "category": "cdn",
        "headers": {"server": ["cdn77"], "x-cdn77": [".*"]},
        "cookies": ["cdn77_"],
        "body": ["cdn77", "datacamp"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["cdn77"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS60068"],
        "confidence_weight": 0.75,
    },
    "BunnyCDN": {
        "category": "cdn",
        "headers": {"server": ["bunnycd"], "cdn-pullzone": [".*"], "cdn-requestid": [".*"]},
        "cookies": ["bunny_"],
        "body": ["bunnycdn", "bunny"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["bunnycdn"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS200325"],
        "confidence_weight": 0.75,
    },
    "KeyCDN": {
        "category": "cdn",
        "headers": {"server": ["keycdn"], "x-keycdn": [".*"]},
        "cookies": ["keycdn_"],
        "body": ["keycdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["keycdn"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS60068"],
        "confidence_weight": 0.75,
    },
    "Gcore": {
        "category": "cloud",
        "headers": {"server": ["gcore"], "x-gcore": [".*"]},
        "cookies": ["gcore_"],
        "body": ["gcore", "gcore labs"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["gcore"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS199524"],
        "confidence_weight": 0.8,
    },
    "Datadome": {
        "category": "cloud",
        "headers": {"server": ["datadome"], "x-datadome": [".*"], "x-datadome-captcha": [".*"]},
        "cookies": ["datadome", "datadome_session"],
        "body": ["datadome", "dd-api-key", "captcha"],
        "status_codes": [403, 503, 429],
        "title": ["datadome", "please verify you are a human"],
        "active_probe": {"path": "/", "contains": ["datadome"]},
        "behavior": {"challenge": "captcha", "cookie_name": "datadome"},
        "asn": [],
        "confidence_weight": 0.95,
    },
    "PerimeterX (HUMAN)": {
        "category": "cloud",
        "headers": {"server": [".*"], "x-px": [".*"], "x-px-jp": [".*"]},
        "cookies": ["_px", "_pxhd", "_pxff", "_px3", "_px2"],
        "body": ["perimeterx", "px-captcha", "human security", "press & hold"],
        "status_codes": [403, 503, 429],
        "title": ["px-captcha", "are you human"],
        "active_probe": {"path": "/", "contains": ["perimeterx"]},
        "behavior": {"challenge": "javascript", "cookie_name": "_px3"},
        "asn": [],
        "confidence_weight": 0.95,
    },
    "Kasada": {
        "category": "cloud",
        "headers": {"server": [".*"], "x-kasada": [".*"], "kp": [".*"]},
        "cookies": ["kasada", "_kps_", "kpsdk"],
        "body": ["kasada", "bot detect", "kpsdk"],
        "status_codes": [403, 429],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["kasada"]},
        "behavior": {"challenge": "javascript", "cookie_name": "kpsdk"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "Wallarm": {
        "category": "cloud",
        "headers": {"server": ["wallarm"], "x-wallarm": [".*"]},
        "cookies": ["wallarm_"],
        "body": ["wallarm", "request blocked"],
        "status_codes": [403, 429],
        "title": ["request blocked"],
        "active_probe": {"path": "/", "contains": ["wallarm"]},
        "behavior": {"challenge": "none", "cookie_name": "wallarm_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Reblaze": {
        "category": "cloud",
        "headers": {"server": ["reblaze"], "x-reblaze": [".*"]},
        "cookies": ["reblaze_"],
        "body": ["reblaze", "request blocked"],
        "status_codes": [403, 503],
        "title": ["request blocked", "access denied"],
        "active_probe": {"path": "/", "contains": ["reblaze"]},
        "behavior": {"challenge": "javascript", "cookie_name": "reblaze_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Distil Networks": {
        "category": "cloud",
        "headers": {"server": ["distil"], "x-distil-cs": [".*"]},
        "cookies": ["distil_", "dtCookie"],
        "body": ["distil", "pardon our interruption"],
        "status_codes": [403, 503],
        "title": ["pardon our interruption", "distil"],
        "active_probe": {"path": "/", "contains": ["distil"]},
        "behavior": {"challenge": "javascript", "cookie_name": "distil_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "Shape Security": {
        "category": "cloud",
        "headers": {"server": ["shape"], "x-shape": [".*"]},
        "cookies": ["shape_", "sky_"],
        "body": ["shape security", "signal science"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["shape"]},
        "behavior": {"challenge": "javascript", "cookie_name": "shape_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Signal Sciences": {
        "category": "cloud",
        "headers": {"server": [".*"], "x-signal-sciences": [".*"]},
        "cookies": ["_sigil_", "ss_"],
        "body": ["signal sciences", "request blocked"],
        "status_codes": [403, 429],
        "title": ["request blocked"],
        "active_probe": {"path": "/", "contains": ["signal sciences"]},
        "behavior": {"challenge": "none", "cookie_name": "_sigil_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "Teros": {
        "category": "cloud",
        "headers": {"server": ["teros"]},
        "cookies": ["teros_"],
        "body": ["teros", "request blocked"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["teros"]},
        "behavior": {"challenge": "none", "cookie_name": "teros_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "Barracuda": {
        "category": "cloud",
        "headers": {"server": ["barracuda"], "x-barracuda": [".*"]},
        "cookies": ["barra_", "barracuda_"],
        "body": ["barracuda", "web application firewall"],
        "status_codes": [403, 503],
        "title": ["access denied", "request blocked"],
        "active_probe": {"path": "/", "contains": ["barracuda"]},
        "behavior": {"challenge": "none", "cookie_name": "barra_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Cloudbric": {
        "category": "cloud",
        "headers": {"server": ["cloudbric"], "x-cloudbric": [".*"]},
        "cookies": ["cloudbric_"],
        "body": ["cloudbric", "request blocked"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["cloudbric"]},
        "behavior": {"challenge": "javascript", "cookie_name": "cloudbric_"},
        "asn": [],
        "confidence_weight": 0.8,
    },

    # ========================================================================
    # 国产 WAF (Chinese WAF)
    # ========================================================================

    "阿里云WAF": {
        "category": "cloud",
        "headers": {"server": ["tengine", "aliyun"], "x-alicdn": [".*"], "via": ["aliyun"]},
        "cookies": ["aliyungf_tc", "acw_tc", "龙华_waf"],
        "body": ["aliyun", "waf", "请求被拦截", "您的请求带有不合法参数"],
        "status_codes": [403, 405, 503],
        "title": ["请求被拦截", "阿里云web应用防火墙"],
        "active_probe": {"path": "/", "contains": ["aliyun"]},
        "behavior": {"challenge": "javascript", "cookie_name": "acw_tc"},
        "asn": ["AS37963"],
        "confidence_weight": 0.95,
    },
    "腾讯云WAF": {
        "category": "cloud",
        "headers": {"server": ["tencent"], "x-tencent": [".*"], "via": ["tencent"]},
        "cookies": ["tencentwaf_", "qcloudwaf_"],
        "body": ["腾讯云", "tencent", "请求被拦截", "web应用防火墙"],
        "status_codes": [403, 405, 503],
        "title": ["请求被拦截", "腾讯云waf"],
        "active_probe": {"path": "/", "contains": ["tencent"]},
        "behavior": {"challenge": "javascript", "cookie_name": "tencentwaf_"},
        "asn": ["AS45090"],
        "confidence_weight": 0.95,
    },
    "百度云WAF": {
        "category": "cloud",
        "headers": {"server": ["baidu", "yunjiasu"], "x-bd": [".*"]},
        "cookies": ["baidu_waf", "bd_"],
        "body": ["百度云", "baidu", "请求被拦截", "yunjiasu"],
        "status_codes": [403, 405, 503],
        "title": ["请求被拦截", "百度云加速"],
        "active_probe": {"path": "/", "contains": ["baidu"]},
        "behavior": {"challenge": "javascript", "cookie_name": "baidu_waf"},
        "asn": ["AS38365"],
        "confidence_weight": 0.9,
    },
    "华为云WAF": {
        "category": "cloud",
        "headers": {"server": ["huawei", "hws"], "x-hw": [".*"]},
        "cookies": ["huawei_waf", "hwclouds_"],
        "body": ["华为云", "huawei", "请求被拦截", "web应用防火墙"],
        "status_codes": [403, 405, 503],
        "title": ["请求被拦截", "华为云waf"],
        "active_probe": {"path": "/", "contains": ["huawei"]},
        "behavior": {"challenge": "javascript", "cookie_name": "huawei_waf"},
        "asn": ["AS136907"],
        "confidence_weight": 0.9,
    },
    "奇安信WAF": {
        "category": "software",
        "headers": {"server": ["qianxin", "360"]},
        "cookies": ["qianxin_"],
        "body": ["奇安信", "网神", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "奇安信"],
        "active_probe": {"path": "/", "contains": ["qianxin"]},
        "behavior": {"challenge": "none", "cookie_name": "qianxin_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "深信服WAF": {
        "category": "hardware",
        "headers": {"server": ["sangfor", "sangforwaf"]},
        "cookies": ["sangfor_", "waf_"],
        "body": ["深信服", "sangfor", "请求被拦截", "web应用防火墙"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "深信服waf"],
        "active_probe": {"path": "/", "contains": ["sangfor"]},
        "behavior": {"challenge": "none", "cookie_name": "sangfor_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "长亭雷池": {
        "category": "software",
        "headers": {"server": ["chaitin", "leichi"]},
        "cookies": ["chaitin_", "leichi_"],
        "body": ["长亭", "雷池", "chaitin", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "雷池waf"],
        "active_probe": {"path": "/", "contains": ["chaitin"]},
        "behavior": {"challenge": "none", "cookie_name": "chaitin_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "安恒明御": {
        "category": "hardware",
        "headers": {"server": ["dbappsecurity", "anhen"]},
        "cookies": ["dbapp_", "anhen_"],
        "body": ["安恒", "明御", "dbappsecurity", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "安恒明御"],
        "active_probe": {"path": "/", "contains": ["dbappsecurity"]},
        "behavior": {"challenge": "none", "cookie_name": "dbapp_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "绿盟WAF": {
        "category": "hardware",
        "headers": {"server": ["nsfocus", "nsf"]},
        "cookies": ["nsfocus_"],
        "body": ["绿盟", "nsfocus", "请求被拦截", "web应用防火墙"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "绿盟waf"],
        "active_probe": {"path": "/", "contains": ["nsfocus"]},
        "behavior": {"challenge": "none", "cookie_name": "nsfocus_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "启明星辰天清": {
        "category": "hardware",
        "headers": {"server": ["venustech", "tianqing"]},
        "cookies": ["venustech_", "tianqing_"],
        "body": ["启明星辰", "天清", "venustech", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "天清waf"],
        "active_probe": {"path": "/", "contains": ["venustech"]},
        "behavior": {"challenge": "none", "cookie_name": "venustech_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "360企业安全WAF": {
        "category": "software",
        "headers": {"server": ["360", "qihoo"]},
        "cookies": ["360waf_", "qihoo_"],
        "body": ["360", "qihoo", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "360waf"],
        "active_probe": {"path": "/", "contains": ["360"]},
        "behavior": {"challenge": "none", "cookie_name": "360waf_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "网宿WAF": {
        "category": "cloud",
        "headers": {"server": ["wangsu", "chinacache"]},
        "cookies": ["wangsu_"],
        "body": ["网宿", "wangsu", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "网宿waf"],
        "active_probe": {"path": "/", "contains": ["wangsu"]},
        "behavior": {"challenge": "javascript", "cookie_name": "wangsu_"},
        "asn": ["AS24137"],
        "confidence_weight": 0.85,
    },
    "帝联WAF": {
        "category": "cloud",
        "headers": {"server": ["dnion", "dilian"]},
        "cookies": ["dnion_"],
        "body": ["帝联", "dnion", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "帝联waf"],
        "active_probe": {"path": "/", "contains": ["dnion"]},
        "behavior": {"challenge": "none", "cookie_name": "dnion_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "又拍云WAF": {
        "category": "cloud",
        "headers": {"server": ["upyun"], "x-upyun": [".*"]},
        "cookies": ["upyun_"],
        "body": ["又拍云", "upyun", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "又拍云waf"],
        "active_probe": {"path": "/", "contains": ["upyun"]},
        "behavior": {"challenge": "javascript", "cookie_name": "upyun_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "七牛云WAF": {
        "category": "cloud",
        "headers": {"server": ["qiniu"], "x-qiniu": [".*"]},
        "cookies": ["qiniu_"],
        "body": ["七牛云", "qiniu", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "七牛云waf"],
        "active_probe": {"path": "/", "contains": ["qiniu"]},
        "behavior": {"challenge": "javascript", "cookie_name": "qiniu_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "火山引擎WAF": {
        "category": "cloud",
        "headers": {"server": ["volcengine", "bytedance"]},
        "cookies": ["volc_", "tte_"],
        "body": ["火山引擎", "volcengine", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "火山引擎waf"],
        "active_probe": {"path": "/", "contains": ["volcengine"]},
        "behavior": {"challenge": "javascript", "cookie_name": "volc_"},
        "asn": ["AS45090"],
        "confidence_weight": 0.85,
    },
    "金山云WAF": {
        "category": "cloud",
        "headers": {"server": ["kingsoft", "ksyun"]},
        "cookies": ["ksyun_"],
        "body": ["金山云", "ksyun", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "金山云waf"],
        "active_probe": {"path": "/", "contains": ["ksyun"]},
        "behavior": {"challenge": "javascript", "cookie_name": "ksyun_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "UCloud WAF": {
        "category": "cloud",
        "headers": {"server": ["ucloud"]},
        "cookies": ["ucloud_"],
        "body": ["ucloud", "uclo", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "ucloud waf"],
        "active_probe": {"path": "/", "contains": ["ucloud"]},
        "behavior": {"challenge": "javascript", "cookie_name": "ucloud_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "京东云WAF": {
        "category": "cloud",
        "headers": {"server": ["jdcloud", "jingdong"]},
        "cookies": ["jdcloud_"],
        "body": ["京东云", "jdcloud", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "京东云waf"],
        "active_probe": {"path": "/", "contains": ["jdcloud"]},
        "behavior": {"challenge": "javascript", "cookie_name": "jdcloud_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "白山云WAF": {
        "category": "cloud",
        "headers": {"server": ["baishan", "bsc"]},
        "cookies": ["bsc_"],
        "body": ["白山云", "baishan", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "白山云waf"],
        "active_probe": {"path": "/", "contains": ["baishan"]},
        "behavior": {"challenge": "javascript", "cookie_name": "bsc_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "网易云WAF": {
        "category": "cloud",
        "headers": {"server": ["netease", "yd"]},
        "cookies": ["netease_"],
        "body": ["网易", "netease", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "网易云waf"],
        "active_probe": {"path": "/", "contains": ["netease"]},
        "behavior": {"challenge": "javascript", "cookie_name": "netease_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "天翼云WAF": {
        "category": "cloud",
        "headers": {"server": ["ctyun", "esurfing"]},
        "cookies": ["ctyun_"],
        "body": ["天翼云", "ctyun", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "天翼云waf"],
        "active_probe": {"path": "/", "contains": ["ctyun"]},
        "behavior": {"challenge": "javascript", "cookie_name": "ctyun_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "移动云WAF": {
        "category": "cloud",
        "headers": {"server": ["chinamobile", "cmcc"]},
        "cookies": ["cmcc_"],
        "body": ["移动云", "chinamobile", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "移动云waf"],
        "active_probe": {"path": "/", "contains": ["chinamobile"]},
        "behavior": {"challenge": "javascript", "cookie_name": "cmcc_"},
        "asn": ["AS9808"],
        "confidence_weight": 0.8,
    },
    "联通云WAF": {
        "category": "cloud",
        "headers": {"server": ["chinaunicom", "unicom"]},
        "cookies": ["unicom_"],
        "body": ["联通云", "chinaunicom", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "联通云waf"],
        "active_probe": {"path": "/", "contains": ["chinaunicom"]},
        "behavior": {"challenge": "javascript", "cookie_name": "unicom_"},
        "asn": ["AS4837"],
        "confidence_weight": 0.8,
    },
    "青云WAF": {
        "category": "cloud",
        "headers": {"server": ["qingcloud", "yunify"]},
        "cookies": ["qingcloud_"],
        "body": ["青云", "qingcloud", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "青云waf"],
        "active_probe": {"path": "/", "contains": ["qingcloud"]},
        "behavior": {"challenge": "javascript", "cookie_name": "qingcloud_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "西部数码WAF": {
        "category": "cloud",
        "headers": {"server": ["west263", "west"]},
        "cookies": ["west_"],
        "body": ["西部数码", "west263", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "西部数码waf"],
        "active_probe": {"path": "/", "contains": ["west263"]},
        "behavior": {"challenge": "none", "cookie_name": "west_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "中通服WAF": {
        "category": "cloud",
        "headers": {"server": ["ctcc", "ccs"]},
        "cookies": ["ctcc_"],
        "body": ["中通服", "ctcc", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "中通服waf"],
        "active_probe": {"path": "/", "contains": ["ctcc"]},
        "behavior": {"challenge": "none", "cookie_name": "ctcc_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "360网站卫士": {
        "category": "cloud",
        "headers": {"server": ["360wzb", "360"]},
        "cookies": ["__jsluid", "wzb_"],
        "body": ["360网站卫士", "360wzb", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "360网站卫士"],
        "active_probe": {"path": "/", "contains": ["360wzb"]},
        "behavior": {"challenge": "javascript", "cookie_name": "wzb_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "加速乐": {
        "category": "cloud",
        "headers": {"server": ["jiasule"]},
        "cookies": ["__jsluid", "jiasule_"],
        "body": ["加速乐", "jiasule", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "加速乐"],
        "active_probe": {"path": "/", "contains": ["jiasule"]},
        "behavior": {"challenge": "javascript", "cookie_name": "jiasule_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "创宇盾": {
        "category": "cloud",
        "headers": {"server": ["yunaq", "knownsec"]},
        "cookies": ["yunaq_", "cy_"],
        "body": ["创宇盾", "yunaq", "知道创宇", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "创宇盾"],
        "active_probe": {"path": "/", "contains": ["yunaq"]},
        "behavior": {"challenge": "javascript", "cookie_name": "yunaq_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "百度云加速": {
        "category": "cloud",
        "headers": {"server": ["yunjiasu", "baidu"]},
        "cookies": ["__jsluid", "bd_"],
        "body": ["百度云加速", "yunjiasu", "请求被拦截"],
        "status_codes": [403, 503],
        "title": ["请求被拦截", "百度云加速"],
        "active_probe": {"path": "/", "contains": ["yunjiasu"]},
        "behavior": {"challenge": "javascript", "cookie_name": "bd_"},
        "asn": ["AS38365"],
        "confidence_weight": 0.9,
    },
    "阿里云CDN": {
        "category": "cdn",
        "headers": {"server": ["tengine"], "x-alicdn": [".*"], "via": ["aliyun"]},
        "cookies": ["aliyungf_tc"],
        "body": ["alicdn", "aliyun"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["alicdn"]},
        "behavior": {"challenge": "none", "cookie_name": "aliyungf_tc"},
        "asn": ["AS37963"],
        "confidence_weight": 0.7,
    },
    "腾讯云CDN": {
        "category": "cdn",
        "headers": {"server": ["tencent"], "x-tencent": [".*"]},
        "cookies": ["tencent_"],
        "body": ["tencent", "cdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["tencent"]},
        "behavior": {"challenge": "none", "cookie_name": "tencent_"},
        "asn": ["AS45090"],
        "confidence_weight": 0.7,
    },

    # ========================================================================
    # 开源 / 软件 WAF (Open Source / Software WAF)
    # ========================================================================

    "ModSecurity": {
        "category": "software",
        "headers": {"server": ["apache", "nginx"], "x-powered-by": [".*"]},
        "cookies": [],
        "body": ["mod_security", "modsecurity", "not acceptable", "id:", "Mod_Security"],
        "status_codes": [403, 400, 406, 500],
        "title": ["not acceptable", "forbidden"],
        "active_probe": {"path": "/", "contains": ["mod_security"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "ModSecurity v3": {
        "category": "software",
        "headers": {"server": ["nginx"], "x-powered-by": [".*"]},
        "cookies": [],
        "body": ["modsecurity", "mod_security v3", "libmodsecurity"],
        "status_codes": [403, 400, 406],
        "title": ["not acceptable", "forbidden"],
        "active_probe": {"path": "/", "contains": ["libmodsecurity"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "ModSecurity-nginx": {
        "category": "software",
        "headers": {"server": ["nginx"]},
        "cookies": [],
        "body": ["modsecurity", "nginx-mod-security"],
        "status_codes": [403, 400, 406],
        "title": ["forbidden", "not acceptable"],
        "active_probe": {"path": "/", "contains": ["modsecurity"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "NAXSI": {
        "category": "software",
        "headers": {"server": ["nginx"]},
        "cookies": [],
        "body": ["naxsi", "naxsi block"],
        "status_codes": [403, 400],
        "title": ["forbidden", "request blocked"],
        "active_probe": {"path": "/?a=../", "contains": ["naxsi"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Naxsi nginx": {
        "category": "software",
        "headers": {"server": ["nginx-naxsi", "nginx"]},
        "cookies": [],
        "body": ["naxsi", "naxsi_block"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/?a=../", "contains": ["naxsi"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Shadow Daemon": {
        "category": "software",
        "headers": {"server": [".*"]},
        "cookies": ["shadowd_"],
        "body": ["shadow daemon", "shadowd"],
        "status_codes": [403, 400],
        "title": ["forbidden", "request blocked"],
        "active_probe": {"path": "/", "contains": ["shadow daemon"]},
        "behavior": {"challenge": "none", "cookie_name": "shadowd_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Shadow Daemon PHP": {
        "category": "software",
        "headers": {"server": ["apache", "nginx"]},
        "cookies": ["shadowd_php"],
        "body": ["shadow daemon php", "shadowd"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["shadowd"]},
        "behavior": {"challenge": "none", "cookie_name": "shadowd_php"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "WebKnight": {
        "category": "software",
        "headers": {"server": ["webknight", "aqtronix"]},
        "cookies": [],
        "body": ["webknight", "aqtronix", "webknight ism"],
        "status_codes": [403, 400],
        "title": ["forbidden", "webknight"],
        "active_probe": {"path": "/", "contains": ["webknight"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "AQtronix WebKnight": {
        "category": "software",
        "headers": {"server": ["webknight"]},
        "cookies": [],
        "body": ["aqtronix webknight", "webknight"],
        "status_codes": [403, 400],
        "title": ["forbidden", "webknight"],
        "active_probe": {"path": "/", "contains": ["webknight"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "PHPIDS": {
        "category": "software",
        "headers": {"server": ["apache", "nginx"]},
        "cookies": ["phpids_"],
        "body": ["phpids", "php-ids"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["phpids"]},
        "behavior": {"challenge": "none", "cookie_name": "phpids_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "IronBee": {
        "category": "software",
        "headers": {"server": ["ironbee"]},
        "cookies": ["ironbee_"],
        "body": ["ironbee", "iron bee"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["ironbee"]},
        "behavior": {"challenge": "none", "cookie_name": "ironbee_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "nginx-mod-security": {
        "category": "software",
        "headers": {"server": ["nginx"]},
        "cookies": [],
        "body": ["mod_security", "modsecurity"],
        "status_codes": [403, 406],
        "title": ["forbidden", "not acceptable"],
        "active_probe": {"path": "/", "contains": ["mod_security"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Coraza": {
        "category": "software",
        "headers": {"server": ["coraza"]},
        "cookies": [],
        "body": ["coraza", "coraza waf"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["coraza"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Coraza Caddy": {
        "category": "software",
        "headers": {"server": ["caddy", "coraza"]},
        "cookies": [],
        "body": ["coraza", "coraza-spoa"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["coraza"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Curiefense": {
        "category": "software",
        "headers": {"server": ["curiefense", "curie"]},
        "cookies": ["curiefense_"],
        "body": ["curiefense", "curie"],
        "status_codes": [403, 400],
        "title": ["forbidden", "request blocked"],
        "active_probe": {"path": "/", "contains": ["curiefense"]},
        "behavior": {"challenge": "none", "cookie_name": "curiefense_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "open-appsec": {
        "category": "software",
        "headers": {"server": ["open-appsec"]},
        "cookies": ["openappsec_"],
        "body": ["open-appsec", "open appsec"],
        "status_codes": [403, 400],
        "title": ["forbidden", "request blocked"],
        "active_probe": {"path": "/", "contains": ["open-appsec"]},
        "behavior": {"challenge": "none", "cookie_name": "openappsec_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "DotDefender": {
        "category": "software",
        "headers": {"server": ["dotdefender"]},
        "cookies": ["dotdefender_"],
        "body": ["dotdefender", "dot defender"],
        "status_codes": [403, 400],
        "title": ["forbidden", "dotdefender"],
        "active_probe": {"path": "/", "contains": ["dotdefender"]},
        "behavior": {"challenge": "none", "cookie_name": "dotdefender_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "AppSensor": {
        "category": "software",
        "headers": {"server": [".*"]},
        "cookies": ["appsensor_"],
        "body": ["appsensor"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["appsensor"]},
        "behavior": {"challenge": "none", "cookie_name": "appsensor_"},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "WebARX": {
        "category": "software",
        "headers": {"server": ["webarx"]},
        "cookies": ["webarx_"],
        "body": ["webarx", "web arx"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["webarx"]},
        "behavior": {"challenge": "none", "cookie_name": "webarx_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "Protect": {
        "category": "software",
        "headers": {"server": ["protect"]},
        "cookies": ["protect_"],
        "body": ["protect", "web protect"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["protect"]},
        "behavior": {"challenge": "none", "cookie_name": "protect_"},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "Snuffleupagus": {
        "category": "software",
        "headers": {"server": ["apache", "nginx"]},
        "cookies": [],
        "body": ["snuffleupagus"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["snuffleupagus"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "Lua-resty-waf": {
        "category": "software",
        "headers": {"server": ["openresty", "nginx"]},
        "cookies": [],
        "body": ["lua-resty-waf", "resty waf"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["resty-waf"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "WAFW00F detected": {
        "category": "software",
        "headers": {"server": [".*"]},
        "cookies": [],
        "body": ["wafw00f"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["wafw00f"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.5,
    },
    "binarysec": {
        "category": "software",
        "headers": {"server": ["binarysec"], "x-binarysec-via": [".*"]},
        "cookies": ["binarysec_"],
        "body": ["binarysec", "binary security"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["binarysec"]},
        "behavior": {"challenge": "none", "cookie_name": "binarysec_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "URLScan": {
        "category": "software",
        "headers": {"server": ["microsoft-iis"], "x-powered-by": ["urlscan"]},
        "cookies": [],
        "body": ["urlscan", "rejected-by-urlscan"],
        "status_codes": [403, 400, 404],
        "title": ["forbidden", "rejected"],
        "active_probe": {"path": "/", "contains": ["urlscan"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.85,
    },

    # ========================================================================
    # 硬件 WAF (Hardware WAF)
    # ========================================================================

    "F5 BIG-IP ASM": {
        "category": "hardware",
        "headers": {"server": ["bigip"], "x-cdn": ["f5"]},
        "cookies": ["TS01", "BIGipServer"],
        "body": ["f5", "big-ip", "asm", "the requested url was rejected"],
        "status_codes": [403, 503, 400],
        "title": ["request rejected"],
        "active_probe": {"path": "/", "contains": ["bigip"]},
        "behavior": {"challenge": "none", "cookie_name": "BIGipServer"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "F5 BIG-IP": {
        "category": "hardware",
        "headers": {"server": ["bigip"]},
        "cookies": ["BIGipServer", "TS01"],
        "body": ["big-ip", "f5 networks"],
        "status_codes": [403, 503],
        "title": ["error", "forbidden"],
        "active_probe": {"path": "/", "contains": ["bigip"]},
        "behavior": {"challenge": "none", "cookie_name": "BIGipServer"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Citrix NetScaler (hardware)": {
        "category": "hardware",
        "headers": {"server": ["citrix", "netscaler"]},
        "cookies": ["NSC_", "citrix_ns_id"],
        "body": ["citrix", "netscaler", "appfw"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["netscaler"]},
        "behavior": {"challenge": "none", "cookie_name": "NSC_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Citrix ADC": {
        "category": "hardware",
        "headers": {"server": ["citrix", "adc"]},
        "cookies": ["NSC_"],
        "body": ["citrix", "adc", "appfw"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["citrix"]},
        "behavior": {"challenge": "none", "cookie_name": "NSC_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Fortinet FortiWeb (hardware)": {
        "category": "hardware",
        "headers": {"server": ["fortiweb"]},
        "cookies": ["fortiweb_"],
        "body": ["fortiweb", "fortinet"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["fortiweb"]},
        "behavior": {"challenge": "none", "cookie_name": "fortiweb_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Fortinet FortiADC": {
        "category": "hardware",
        "headers": {"server": ["fortiadc", "fortinet"]},
        "cookies": ["fortiadc_"],
        "body": ["fortiadc", "fortinet"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["fortiadc"]},
        "behavior": {"challenge": "none", "cookie_name": "fortiadc_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Imperva SecureSphere": {
        "category": "hardware",
        "headers": {"server": ["securesphere", "imperva"]},
        "cookies": ["incap_ses_", "imperva_"],
        "body": ["securesphere", "imperva", "request blocked"],
        "status_codes": [403, 503],
        "title": ["request blocked", "access denied"],
        "active_probe": {"path": "/", "contains": ["securesphere"]},
        "behavior": {"challenge": "none", "cookie_name": "imperva_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "Radware AppWall": {
        "category": "hardware",
        "headers": {"server": ["appwall", "radware"]},
        "cookies": ["appwall_"],
        "body": ["appwall", "radware"],
        "status_codes": [403, 503],
        "title": ["access denied", "request blocked"],
        "active_probe": {"path": "/", "contains": ["appwall"]},
        "behavior": {"challenge": "none", "cookie_name": "appwall_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Barracuda Web Application Firewall": {
        "category": "hardware",
        "headers": {"server": ["barracuda"]},
        "cookies": ["barra_"],
        "body": ["barracuda", "web application firewall"],
        "status_codes": [403, 503],
        "title": ["access denied", "request blocked"],
        "active_probe": {"path": "/", "contains": ["barracuda"]},
        "behavior": {"challenge": "none", "cookie_name": "barra_"},
        "asn": [],
        "confidence_weight": 0.9,
    },
    "Cisco ACE": {
        "category": "hardware",
        "headers": {"server": ["cisco", "ace"]},
        "cookies": ["cisco_"],
        "body": ["cisco", "ace", "application control engine"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["cisco"]},
        "behavior": {"challenge": "none", "cookie_name": "cisco_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Juniper WebApp Secure": {
        "category": "hardware",
        "headers": {"server": ["juniper"]},
        "cookies": ["juniper_"],
        "body": ["juniper", "webapp secure"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["juniper"]},
        "behavior": {"challenge": "none", "cookie_name": "juniper_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Dell SonicWALL": {
        "category": "hardware",
        "headers": {"server": ["sonicwall", "dell"]},
        "cookies": ["sonicwall_"],
        "body": ["sonicwall", "dell"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["sonicwall"]},
        "behavior": {"challenge": "none", "cookie_name": "sonicwall_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Trend Micro InterScan": {
        "category": "hardware",
        "headers": {"server": ["trendmicro", "interscan"]},
        "cookies": ["trend_"],
        "body": ["trend micro", "interscan"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["interscan"]},
        "behavior": {"challenge": "none", "cookie_name": "trend_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Hillstone": {
        "category": "hardware",
        "headers": {"server": ["hillstone"]},
        "cookies": ["hillstone_"],
        "body": ["hillstone", "山石网科"],
        "status_codes": [403, 503],
        "title": ["access denied", "请求被拦截"],
        "active_probe": {"path": "/", "contains": ["hillstone"]},
        "behavior": {"challenge": "none", "cookie_name": "hillstone_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Sangfor (hardware)": {
        "category": "hardware",
        "headers": {"server": ["sangfor"]},
        "cookies": ["sangfor_"],
        "body": ["深信服", "sangfor"],
        "status_codes": [403, 503],
        "title": ["请求被拦截"],
        "active_probe": {"path": "/", "contains": ["sangfor"]},
        "behavior": {"challenge": "none", "cookie_name": "sangfor_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "Venustech": {
        "category": "hardware",
        "headers": {"server": ["venustech"]},
        "cookies": ["venustech_"],
        "body": ["启明星辰", "venustech"],
        "status_codes": [403, 503],
        "title": ["请求被拦截"],
        "active_probe": {"path": "/", "contains": ["venustech"]},
        "behavior": {"challenge": "none", "cookie_name": "venustech_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Topsec": {
        "category": "hardware",
        "headers": {"server": ["topsec"]},
        "cookies": ["topsec_"],
        "body": ["天融信", "topsec"],
        "status_codes": [403, 503],
        "title": ["请求被拦截"],
        "active_probe": {"path": "/", "contains": ["topsec"]},
        "behavior": {"challenge": "none", "cookie_name": "topsec_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "DBAPPSecurity": {
        "category": "hardware",
        "headers": {"server": ["dbappsecurity"]},
        "cookies": ["dbapp_"],
        "body": ["安恒", "dbappsecurity"],
        "status_codes": [403, 503],
        "title": ["请求被拦截"],
        "active_probe": {"path": "/", "contains": ["dbappsecurity"]},
        "behavior": {"challenge": "none", "cookie_name": "dbapp_"},
        "asn": [],
        "confidence_weight": 0.85,
    },
    "A10 Thunder": {
        "category": "hardware",
        "headers": {"server": ["a10", "thunder"]},
        "cookies": ["a10_"],
        "body": ["a10", "thunder", "a10 networks"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["a10"]},
        "behavior": {"challenge": "none", "cookie_name": "a10_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Check Point": {
        "category": "hardware",
        "headers": {"server": ["checkpoint", "check point"]},
        "cookies": ["checkpoint_"],
        "body": ["check point", "checkpoint"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["checkpoint"]},
        "behavior": {"challenge": "none", "cookie_name": "checkpoint_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Palo Alto": {
        "category": "hardware",
        "headers": {"server": ["paloalto", "palo alto"]},
        "cookies": ["pan_"],
        "body": ["palo alto", "paloalto"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["paloalto"]},
        "behavior": {"challenge": "none", "cookie_name": "pan_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "Sophos UTM": {
        "category": "hardware",
        "headers": {"server": ["sophos", "astaro"]},
        "cookies": ["sophos_"],
        "body": ["sophos", "utm"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["sophos"]},
        "behavior": {"challenge": "none", "cookie_name": "sophos_"},
        "asn": [],
        "confidence_weight": 0.8,
    },

    # ========================================================================
    # 其他 / 新兴 WAF (Other / Emerging)
    # ========================================================================

    "CDNetworks": {
        "category": "cloud",
        "headers": {"server": ["cdnetworks"], "x-cdnetworks": [".*"]},
        "cookies": ["cdnetworks_"],
        "body": ["cdnetworks", "request blocked"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["cdnetworks"]},
        "behavior": {"challenge": "none", "cookie_name": "cdnetworks_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "ArvanCloud": {
        "category": "cloud",
        "headers": {"server": ["arvancloud", "arvan"]},
        "cookies": ["arvan_"],
        "body": ["arvancloud", "arvan"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["arvancloud"]},
        "behavior": {"challenge": "javascript", "cookie_name": "arvan_"},
        "asn": ["AS208295"],
        "confidence_weight": 0.8,
    },
    "HiberniaCDN": {
        "category": "cdn",
        "headers": {"server": ["hiberniacdn"]},
        "cookies": ["hibernia_"],
        "body": ["hiberniacdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["hiberniacdn"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "Leaseweb": {
        "category": "cdn",
        "headers": {"server": ["leaseweb"]},
        "cookies": ["leaseweb_"],
        "body": ["leaseweb"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["leaseweb"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS60626"],
        "confidence_weight": 0.7,
    },
    "OnApp": {
        "category": "cdn",
        "headers": {"server": ["onapp"]},
        "cookies": ["onapp_"],
        "body": ["onapp"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["onapp"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "Tata Communications": {
        "category": "cdn",
        "headers": {"server": ["tata"]},
        "cookies": ["tata_"],
        "body": ["tata communications"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["tata"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS6459"],
        "confidence_weight": 0.7,
    },
    "Lumen/CenturyLink": {
        "category": "cdn",
        "headers": {"server": ["centurylink", "lumen"]},
        "cookies": ["lumen_"],
        "body": ["centurylink", "lumen"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["centurylink"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS209"],
        "confidence_weight": 0.75,
    },
    "CacheFly": {
        "category": "cdn",
        "headers": {"server": ["cachefly"], "x-cachefly": [".*"]},
        "cookies": ["cachefly_"],
        "body": ["cachefly"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["cachefly"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS30081"],
        "confidence_weight": 0.7,
    },
    "Yottaa": {
        "category": "cloud",
        "headers": {"server": ["yottaa"], "x-yottaa": [".*"]},
        "cookies": ["yottaa_"],
        "body": ["yottaa"],
        "status_codes": [403, 503],
        "title": ["error", "access denied"],
        "active_probe": {"path": "/", "contains": ["yottaa"]},
        "behavior": {"challenge": "javascript", "cookie_name": "yottaa_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "Section.io": {
        "category": "cloud",
        "headers": {"server": ["section.io", "section"]},
        "cookies": ["section_"],
        "body": ["section.io", "varnish"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["section.io"]},
        "behavior": {"challenge": "none", "cookie_name": "section_"},
        "asn": [],
        "confidence_weight": 0.75,
    },
    "Instart": {
        "category": "cloud",
        "headers": {"server": ["instart"]},
        "cookies": ["instart_"],
        "body": ["instart", "instart logic"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["instart"]},
        "behavior": {"challenge": "javascript", "cookie_name": "instart_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "PageSense": {
        "category": "cloud",
        "headers": {"server": ["pagesense"]},
        "cookies": ["pagesense_"],
        "body": ["pagesense"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["pagesense"]},
        "behavior": {"challenge": "none", "cookie_name": "pagesense_"},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "SUCURI Firewall": {
        "category": "cloud",
        "headers": {"server": ["sucuri"], "x-sucuri-id": [".*"]},
        "cookies": ["sucuri_cloudproxy"],
        "body": ["sucuri", "website firewall"],
        "status_codes": [403, 503, 406],
        "title": ["access denied - sucuri"],
        "active_probe": {"path": "/", "contains": ["sucuri"]},
        "behavior": {"challenge": "javascript", "cookie_name": "sucuri_cloudproxy"},
        "asn": ["AS399471"],
        "confidence_weight": 0.9,
    },
    "Edgecast ECDN": {
        "category": "cdn",
        "headers": {"server": ["edgecast", "ecd"]},
        "cookies": ["ecd_"],
        "body": ["edgecast", "verizon"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["edgecast"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS15133"],
        "confidence_weight": 0.75,
    },
    "Medianova": {
        "category": "cdn",
        "headers": {"server": ["medianova"]},
        "cookies": ["mn_"],
        "body": ["medianova", "mncdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["medianova"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS59817"],
        "confidence_weight": 0.7,
    },
    "BelugaCDN": {
        "category": "cdn",
        "headers": {"server": ["belugacdn"]},
        "cookies": ["beluga_"],
        "body": ["belugacdn", "beluga"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["belugacdn"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "Myra Security": {
        "category": "cloud",
        "headers": {"server": ["myra"], "x-myra": [".*"]},
        "cookies": ["myra_"],
        "body": ["myra security", "myrasecurity"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["myra"]},
        "behavior": {"challenge": "javascript", "cookie_name": "myra_"},
        "asn": ["AS49697"],
        "confidence_weight": 0.85,
    },
    "ddos-guard": {
        "category": "cloud",
        "headers": {"server": ["ddos-guard"]},
        "cookies": ["ddos_guard_", "__ddg_"],
        "body": ["ddos-guard", "ddg"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["ddos-guard"]},
        "behavior": {"challenge": "javascript", "cookie_name": "__ddg_"},
        "asn": ["AS60068"],
        "confidence_weight": 0.85,
    },
    "Incapsula": {
        "category": "cloud",
        "headers": {"server": ["incapsula"], "x-iinfo": [".*"], "x-cdn": ["incapsula"]},
        "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
        "body": ["incapsula", "request blocked", "powered by incapsula"],
        "status_codes": [403, 503, 406],
        "title": ["request blocked", "incapsula incident"],
        "active_probe": {"path": "/", "contains": ["incapsula"]},
        "behavior": {"challenge": "javascript", "cookie_name": "incap_ses_"},
        "asn": ["AS19551"],
        "confidence_weight": 0.95,
    },
    "Cloudflare DDoS": {
        "category": "cloud",
        "headers": {"server": ["cloudflare"], "cf-ray": [".*"], "cf-mitigated": ["ddos"]},
        "cookies": ["__cf_bm", "cf_clearance"],
        "body": ["cloudflare", "ddos protection", "rate limit"],
        "status_codes": [429, 503, 403],
        "title": ["attention required! | cloudflare"],
        "active_probe": {"path": "/cdn-cgi/trace", "contains": ["cf-ray"]},
        "behavior": {"challenge": "javascript", "cookie_name": "cf_clearance"},
        "asn": ["AS13335"],
        "confidence_weight": 0.9,
    },
    "AWS Shield Advanced": {
        "category": "cloud",
        "headers": {"x-amzn-requestid": [".*"], "x-amz-cf-id": [".*"]},
        "cookies": ["aws-waf-token"],
        "body": ["aws shield", "request blocked"],
        "status_codes": [403, 429],
        "title": ["request blocked"],
        "active_probe": {"path": "/", "contains": ["x-amzn-requestid"]},
        "behavior": {"challenge": "token", "cookie_name": "aws-waf-token"},
        "asn": ["AS16509"],
        "confidence_weight": 0.85,
    },
    "Cloudfront": {
        "category": "cdn",
        "headers": {"server": ["cloudfront"], "via": ["cloudfront"], "x-amz-cf-id": [".*"]},
        "cookies": ["aws-waf-token"],
        "body": ["cloudfront", "error", "request blocked"],
        "status_codes": [403, 503, 400],
        "title": ["error", "request blocked"],
        "active_probe": {"path": "/", "contains": ["cloudfront"]},
        "behavior": {"challenge": "none", "cookie_name": "aws-waf-token"},
        "asn": ["AS16509"],
        "confidence_weight": 0.8,
    },
    "Google Cloud CDN": {
        "category": "cdn",
        "headers": {"server": ["google"], "via": ["google"], "x-google": [".*"]},
        "cookies": ["gclb"],
        "body": ["google cloud", "gclb"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["google"]},
        "behavior": {"challenge": "none", "cookie_name": "gclb"},
        "asn": ["AS15169"],
        "confidence_weight": 0.75,
    },
    "Azure CDN": {
        "category": "cdn",
        "headers": {"server": ["microsoft", "azure"], "x-azure-ref": [".*"]},
        "cookies": ["azure_"],
        "body": ["azure cdn", "microsoft"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["x-azure-ref"]},
        "behavior": {"challenge": "none", "cookie_name": "azure_"},
        "asn": ["AS8075"],
        "confidence_weight": 0.75,
    },
    "Aliyun Shield": {
        "category": "cloud",
        "headers": {"server": ["tengine", "aliyun"], "x-alicdn": [".*"]},
        "cookies": ["aliyungf_tc", "acw_tc"],
        "body": ["aliyun shield", "阿里云高防", "anti-bot"],
        "status_codes": [403, 405, 503],
        "title": ["请求被拦截", "error"],
        "active_probe": {"path": "/", "contains": ["aliyun"]},
        "behavior": {"challenge": "javascript", "cookie_name": "acw_tc"},
        "asn": ["AS37963"],
        "confidence_weight": 0.85,
    },
    "Tencent Dayu": {
        "category": "cloud",
        "headers": {"server": ["tencent"], "x-tencent": [".*"]},
        "cookies": ["dayu_", "tencent_"],
        "body": ["腾讯大禹", "dayu", "tencent"],
        "status_codes": [403, 405, 503],
        "title": ["请求被拦截", "error"],
        "active_probe": {"path": "/", "contains": ["tencent"]},
        "behavior": {"challenge": "javascript", "cookie_name": "dayu_"},
        "asn": ["AS45090"],
        "confidence_weight": 0.85,
    },
    "Highwinds": {
        "category": "cdn",
        "headers": {"server": ["highwinds", "hwcdn"]},
        "cookies": ["hwcdn_"],
        "body": ["highwinds", "hwcdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["highwinds"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS33438"],
        "confidence_weight": 0.75,
    },
    "Rackspace": {
        "category": "cdn",
        "headers": {"server": ["rackspace"]},
        "cookies": ["rackspace_"],
        "body": ["rackspace"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["rackspace"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS27357"],
        "confidence_weight": 0.7,
    },
    "Limelight": {
        "category": "cdn",
        "headers": {"server": ["limelight", "llnw"]},
        "cookies": ["llnw_"],
        "body": ["limelight", "llnw"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["limelight"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS22822"],
        "confidence_weight": 0.75,
    },
    "Mirror Image": {
        "category": "cdn",
        "headers": {"server": ["mirrorimage"]},
        "cookies": ["mirror_"],
        "body": ["mirror image"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["mirror image"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.65,
    },
    "SurgeCDN": {
        "category": "cdn",
        "headers": {"server": ["surge"]},
        "cookies": ["surge_"],
        "body": ["surge", "surgecdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["surge"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": [],
        "confidence_weight": 0.65,
    },
    "Microsoft Azure CDN": {
        "category": "cdn",
        "headers": {"server": ["microsoft", "azure"], "x-azure-ref": [".*"], "x-cache": [".*"]},
        "cookies": ["azurecd_"],
        "body": ["azure cdn", "microsoft"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["x-azure-ref"]},
        "behavior": {"challenge": "none", "cookie_name": "azurecd_"},
        "asn": ["AS8075"],
        "confidence_weight": 0.75,
    },
    "Verizon Edgecast": {
        "category": "cdn",
        "headers": {"server": ["edgecast", "verizon"], "x-ec-debug": [".*"]},
        "cookies": ["ecv_"],
        "body": ["verizon edgecast", "edgecast"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["edgecast"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS15133"],
        "confidence_weight": 0.8,
    },
    "StackPath CDN": {
        "category": "cdn",
        "headers": {"server": ["stackpath"], "x-sp-url": [".*"]},
        "cookies": ["spcdn_"],
        "body": ["stackpath", "maxcdn"],
        "status_codes": [403, 503],
        "title": ["error"],
        "active_probe": {"path": "/", "contains": ["stackpath"]},
        "behavior": {"challenge": "none", "cookie_name": ""},
        "asn": ["AS20454"],
        "confidence_weight": 0.8,
    },
    "CDNetworks Cloud": {
        "category": "cloud",
        "headers": {"server": ["cdnetworks"], "x-cdnetworks": [".*"]},
        "cookies": ["cdnc_"],
        "body": ["cdnetworks cloud", "request blocked"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["cdnetworks"]},
        "behavior": {"challenge": "javascript", "cookie_name": "cdnc_"},
        "asn": [],
        "confidence_weight": 0.8,
    },
    "QuadMetrics": {
        "category": "cloud",
        "headers": {"server": ["quadmetrics"]},
        "cookies": ["qm_"],
        "body": ["quadmetrics"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["quadmetrics"]},
        "behavior": {"challenge": "none", "cookie_name": "qm_"},
        "asn": [],
        "confidence_weight": 0.65,
    },
    "Tinfoil Security": {
        "category": "cloud",
        "headers": {"server": ["tinfoil"]},
        "cookies": ["tinfoil_"],
        "body": ["tinfoil security"],
        "status_codes": [403, 503],
        "title": ["access denied"],
        "active_probe": {"path": "/", "contains": ["tinfoil"]},
        "behavior": {"challenge": "none", "cookie_name": "tinfoil_"},
        "asn": [],
        "confidence_weight": 0.7,
    },
    "Netsparker": {
        "category": "software",
        "headers": {"server": ["netsparker"]},
        "cookies": ["netsparker_"],
        "body": ["netsparker"],
        "status_codes": [403, 400],
        "title": ["forbidden"],
        "active_probe": {"path": "/", "contains": ["netsparker"]},
        "behavior": {"challenge": "none", "cookie_name": "netsparker_"},
        "asn": [],
        "confidence_weight": 0.7,
    },
}


# ============================================================================
# 辅助函数 (Helper Functions)
# ============================================================================

def get_stats():
    """返回指纹库统计信息

    Returns:
        dict: 包含 total_wafs, categories, 以及各类别数量统计
    """
    categories = {}
    for waf_name, waf_data in WAF_FINGERPRINTS.items():
        category = waf_data.get("category", "unknown")
        if category not in categories:
            categories[category] = []
        categories[category].append(waf_name)

    category_counts = {cat: len(wafs) for cat, wafs in categories.items()}

    return {
        "total_wafs": len(WAF_FINGERPRINTS),
        "categories": category_counts,
        "categories_detail": categories,
        "version": "2.0",
    }


def get_wafs_by_category(category):
    """按类别返回 WAF 列表

    Args:
        category (str): WAF 类别 (cloud/hardware/software/cdn/saas)

    Returns:
        list: 属于该类别的 WAF 名称列表
    """
    result = []
    for waf_name, waf_data in WAF_FINGERPRINTS.items():
        if waf_data.get("category") == category:
            result.append(waf_name)
    return result


def get_all_waf_names():
    """返回所有 WAF 名称列表

    Returns:
        list: 所有 WAF 名称列表
    """
    return list(WAF_FINGERPRINTS.keys())


def get_waf_fingerprint(waf_name):
    """获取指定 WAF 的指纹信息

    Args:
        waf_name (str): WAF 名称

    Returns:
        dict or None: WAF 指纹信息，不存在则返回 None
    """
    return WAF_FINGERPRINTS.get(waf_name)


def get_all_categories():
    """返回所有 WAF 类别列表

    Returns:
        list: 所有 WAF 类别列表
    """
    categories = set()
    for waf_data in WAF_FINGERPRINTS.values():
        categories.add(waf_data.get("category", "unknown"))
    return sorted(categories)


def search_waf_by_cookie(cookie_name):
    """通过 Cookie 名称搜索匹配的 WAF

    Args:
        cookie_name (str): Cookie 名称

    Returns:
        list: 匹配的 WAF 名称列表
    """
    result = []
    cookie_lower = cookie_name.lower()
    for waf_name, waf_data in WAF_FINGERPRINTS.items():
        for cookie_pattern in waf_data.get("cookies", []):
            if cookie_pattern.lower() in cookie_lower or cookie_lower in cookie_pattern.lower():
                result.append(waf_name)
                break
    return result


def search_waf_by_header(header_name, header_value=""):
    """通过响应头搜索匹配的 WAF

    Args:
        header_name (str): 响应头名称
        header_value (str): 响应头值 (可选)

    Returns:
        list: 匹配的 WAF 名称列表
    """
    result = []
    header_lower = header_name.lower()
    value_lower = header_value.lower() if header_value else ""
    for waf_name, waf_data in WAF_FINGERPRINTS.items():
        for h_name, h_patterns in waf_data.get("headers", {}).items():
            if h_name.lower() == header_lower:
                if not value_lower:
                    result.append(waf_name)
                    break
                for pattern in h_patterns:
                    if pattern == ".*" or pattern.lower() in value_lower:
                        result.append(waf_name)
                        break
                else:
                    continue
                break
    return result


def get_wafs_by_asn(asn):
    """通过 ASN 搜索匹配的 WAF

    Args:
        asn (str): ASN 编号 (例如 "AS13335")

    Returns:
        list: 匹配的 WAF 名称列表
    """
    result = []
    asn_upper = asn.upper()
    for waf_name, waf_data in WAF_FINGERPRINTS.items():
        for waf_asn in waf_data.get("asn", []):
            if waf_asn.upper() == asn_upper:
                result.append(waf_name)
                break
    return result


# ============================================================================
# 模块自测试
# ============================================================================

if __name__ == "__main__":
    stats = get_stats()
    print("=" * 60)
    print("WAF 指纹数据库统计信息")
    print("=" * 60)
    print(f"总 WAF 数量: {stats['total_wafs']}")
    print(f"版本: {stats['version']}")
    print("\n各类别 WAF 数量:")
    for cat, count in sorted(stats["categories"].items()):
        print(f"  {cat}: {count}")
    print("\n所有类别:", get_all_categories())
    print(f"\n所有 WAF 名称列表 ({len(get_all_waf_names())} 个):")
    for i, name in enumerate(get_all_waf_names(), 1):
        print(f"  {i:3d}. {name}")
